# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inara' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for inara

  target 'inaraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'inaraUITests' do
    # Pods for testing
  end

end
